version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: shop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shoppass
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - shop_pgdata:/var/lib/postgresql/data

volumes:
  shop_pgdata: